(library
 (name oebuildlib)
 (wrapped false)
 (modules oebuild_dep_dag oebuild_table oebuild_util oebuild_dag oebuild_dep oebuild_parallel oebuild oebuild_dep_ext)
 (libraries common str unix threads))

(executable
 (name oebuild_tool)
 (public_name oebuild)
 (modules oebuild_tool)
 (libraries common oebuildlib str unix threads))

