(*

  OCamlEditor
  Copyright (C) 2010-2014 Francesco Tovagliari

  This file is part of OCamlEditor.

  OCamlEditor is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  OCamlEditor is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program. If not, see <http://www.gnu.org/licenses/>.

*)

(** Derives dune files from the project model.

    Only directories holding at least one target or one rule are written, so a
    directory of plain assets is never touched. Generated files carry a marker on
    their first line; a dune file without it is left alone and reported, so a
    hand-written one is never clobbered. *)

open Printf

let (//) = Filename.concat

let marker = "; GENERATED BY OCAMLEDITOR - DO NOT EDIT"

(* Emitting bytecode modes adds a second artifact to the default alias for every
   target that builds bytecode. Off until the generated files have been checked
   against the hand-written ones they replace. *)
let emit_bytecode_modes = false

type severity = [ `INFO | `WARN | `ERROR ]

type diagnostic = {
  dg_severity : severity;
  dg_file     : string;
  dg_target   : string;
  dg_task     : string;
  dg_message  : string;
}

type outcome = {
  oc_changed     : string list;  (** files actually rewritten, project-relative *)
  oc_removed     : string list;
  oc_diagnostics : diagnostic list;
}

let string_of_severity = function `INFO -> "INFO" | `WARN -> "WARNING" | `ERROR -> "ERROR"

(** S-expressions, printed in the shape [dune fmt] produces: on one line when it
    fits, otherwise head first and one element per line. *)
module Sexp = struct
  type t = A of string | L of t list

  let width = 78

  let needs_quoting text =
    text = "" ||
    String.exists (function ' ' | '\t' | '\n' | '(' | ')' | '"' | ';' -> true | _ -> false) text

  let quote text =
    let buf = Buffer.create (String.length text + 2) in
    Buffer.add_char buf '"';
    String.iter begin fun c ->
      match c with
      | '"' -> Buffer.add_string buf "\\\""
      | '\\' -> Buffer.add_string buf "\\\\"
      | '\n' -> Buffer.add_string buf "\\n"
      | c -> Buffer.add_char buf c
    end text;
    Buffer.add_char buf '"';
    Buffer.contents buf

  let rec flat = function
    | A text -> if needs_quoting text then quote text else text
    | L items -> "(" ^ String.concat " " (List.map flat items) ^ ")"

  let rec print buf ~indent sexp =
    let oneline = flat sexp in
    if indent + String.length oneline <= width then Buffer.add_string buf oneline
    else
      match sexp with
      | A _ | L [] -> Buffer.add_string buf oneline
      | L (head :: rest) ->
          Buffer.add_char buf '(';
          print buf ~indent:(indent + 1) head;
          List.iter begin fun item ->
            Buffer.add_char buf '\n';
            Buffer.add_string buf (String.make (indent + 1) ' ');
            print buf ~indent:(indent + 1) item
          end rest;
          Buffer.add_char buf ')'

  let to_string sexp =
    let buf = Buffer.create 256 in
    print buf ~indent:0 sexp;
    Buffer.contents buf

  (* Convenience constructors *)
  let field name values = L (A name :: values)
  let atoms names = List.map (fun x -> A x) names
end

(** Paths in the model are relative to the project source directory and may
    point above it. [Rel.from] re-bases one against the directory of the stanza
    or rule that will hold it. [Utils.filename_relative] is not enough: it only
    strips a common prefix and raises otherwise. *)
module Rel = struct
  let segments path =
    path
    |> String.split_on_char '/'
    |> List.concat_map (String.split_on_char '\\')
    |> List.fold_left begin fun acc segment ->
      match segment, acc with
      | ("" | "."), _ -> acc
      | "..", previous :: rest when previous <> ".." -> rest
      | segment, _ -> segment :: acc
    end []
    |> List.rev

  let rec drop_common a b =
    match a, b with
    | x :: xs, y :: ys when x = y -> drop_common xs ys
    | _ -> a, b

  let from ~dir path =
    let dir, path = drop_common (segments dir) (segments path) in
    match List.map (fun _ -> "..") dir @ path with
    | [] -> "."
    | segments -> String.concat "/" segments

  let dirname path =
    match segments path with
    | [] | [_] -> "."
    | segments -> String.concat "/" (List.rev (List.tl (List.rev segments)))
end

(** Names *)

let module_of_path path = path |> Filename.basename |> Filename.remove_extension

let sanitize ?(sep='_') name =
  String.map (fun c ->
      match c with
      | 'a'..'z' | '0'..'9' -> c
      | 'A'..'Z' -> Char.lowercase_ascii c
      | _ -> sep) name

let target_files tg = Utils.split "[ \t\r\n]+" tg.Target.files

(* Where a target's stanza lives, relative to the source directory. Taken from
   [files], not from [outname]: oebuildlib has outname "oebuildlib" but its
   sources are in oebuild/. *)
let target_dir tg =
  match target_files tg with
  | first :: _ -> Rel.dirname first
  | [] -> "."

let dune_name tg =
  match Filename.basename tg.Target.outname with
  | "" -> sanitize tg.Target.name
  | name -> name

let is_library tg =
  match tg.Target.target_type with
  | Target.Library | Target.Pack | Target.Plugin -> true
  | Target.Executable | Target.External -> false

(** Restrictions.

    Mapped onto [enabled_if] following [Oebuild.check_restrictions], whose
    regexps are reused so the two cannot drift apart. The short forms
    [%{system}] and friends are used rather than [%{ocaml-config:...}] because
    dune restricts which variables a public stanza may read, and the short ones
    are allowed. An unrecognized restriction yields [false], which is what
    oebuild does with it. *)
module Restr = struct
  let comparison operator left right =
    let operator = match operator with "=" | ":" -> "=" | _ -> "<>" in
    Sexp.L [Sexp.A operator; Sexp.A left; Sexp.A right]

  let ocaml_variable = function
    | "system" -> "%{system}"
    | "architecture" -> "%{architecture}"
    | "model" -> "%{model}"
    | "version" -> "%{ocaml_version}"
    | property -> sprintf "%%{ocaml-config:%s}" property

  let of_string restriction =
    match restriction with
    | "IS_UNIX" -> Some (comparison "=" "%{os_type}" "Unix")
    | "IS_WIN32" -> Some (comparison "=" "%{os_type}" "Win32")
    | "IS_CYGWIN" -> Some (comparison "=" "%{os_type}" "Cygwin")
    | "HAVE_NATIVE" | "HAS_NATIVE" | "NATIVE" ->
        Some (comparison "=" "%{ocaml-config:native_compiler}" "true")
    | restriction when Str.string_match Oebuild.re_env restriction 0 ->
        let name = Str.matched_group 2 restriction in
        let operator = Str.matched_group 3 restriction in
        let value = Str.matched_group 4 restriction in
        Some (comparison operator (sprintf "%%{env:%s=}" name) value)
    | restriction when Str.string_match Oebuild.re_ocfg restriction 0 ->
        let property = Str.matched_group 2 restriction in
        let operator = Str.matched_group 3 restriction in
        let value = Str.matched_group 4 restriction in
        Some (comparison operator (ocaml_variable property) value)
    | restriction when Str.string_match Oebuild.re_fl_pkg_exist restriction 0 ->
        let packages = Str.split (Utils.regexp "[ ,]+") (Str.matched_group 2 restriction) in
        Some (Sexp.L (Sexp.A "and" ::
                      List.map (fun p -> comparison "=" (sprintf "%%{lib-available:%s}" p) "true")
                        packages))
    | _ -> None
end

(** Libraries.

    oebuild resolves every "libs" entry as an archive filename found through the
    include path, and "package" as findlib packages. In dune both become
    [(libraries ...)] entries, so the archive names that findlib knows under a
    different name have to be translated. *)
let rewrite_library = function
  | "ocamlcommon" | "compiler-libs" -> Some "compiler-libs.common"
  | "ocamlbytecomp" -> Some "compiler-libs.bytecomp"
  | "ocamloptcomp" -> Some "compiler-libs.optcomp"
  | "ocamltoplevel" -> Some "compiler-libs.toplevel"
  | "threads" -> Some "threads.posix"
  | "nums" -> Some "num"
  (* Declare no archive: their findlib packages exist to give a plugin its
     include path, and nothing can be linked from them. *)
  | "ocamldoc" | "odoc" -> None
  | name -> Some name

(** Flags *)

(* Flags [ocamlc] rejects. Keeping them out of (flags ...) matters: the launcher
   target compiles with -compact, which is native-only. *)
let native_only = ["-compact"; "-O2"; "-O3"; "-Oclassic"; "-p"; "-nodynlink"; "-unboxed-types"]
let native_only_with_argument = ["-inline"]

let split_native_flags tokens =
  let rec loop native common = function
    | [] -> List.rev native, List.rev common
    | token :: rest when List.mem token native_only_with_argument ->
        begin
          match rest with
          | argument :: rest -> loop (argument :: token :: native) common rest
          | [] -> loop (token :: native) common []
        end
    | token :: rest when List.mem token native_only -> loop (token :: native) common rest
    | token :: rest -> loop native (token :: common) rest
  in
  loop [] [] tokens

(** Rendering *)

let render proj =
  let diagnostics = ref [] in
  let add severity ?(file="") ?(target="") ?(task="") fmt =
    ksprintf begin fun message ->
      diagnostics := { dg_severity = severity; dg_file = file; dg_target = target;
                       dg_task = task; dg_message = message } :: !diagnostics
    end fmt
  in
  let src = Project.Path.src proj in
  let targets = proj.Prj.targets in
  (* A stanza may only be published if the project declares a package. *)
  let packages =
    try
      Sys.readdir proj.Prj.root
      |> Array.to_list
      |> List.filter (fun name -> Filename.check_suffix name ".opam")
      |> List.map Filename.remove_extension
      |> List.sort compare
    with Sys_error _ -> []
  in
  let internal_libraries =
    targets |> List.filter is_library |> List.map dune_name |> Utils.ListExt.remove_dupl
  in
  (* A local directory named in "includes" stands for whatever library is
     defined there, which is how "includes: oebuild" means oebuildlib. *)
  let library_of_dir =
    targets |> List.filter is_library |> List.map (fun tg -> target_dir tg, dune_name tg)
  in
  let dune_file dir = if dir = "." then "src" // "dune" else "src" // dir // "dune" in

  (* Libraries of a target: packages, archive names, include directories and
     target dependencies, deduplicated, internal ones first. *)
  let libraries_of tg =
    let name = dune_name tg in
    let from_packages =
      Str.split (Utils.regexp "[ ,]+") tg.Target.package
      |> List.filter_map begin fun package ->
        match rewrite_library package with
        | Some rewritten ->
            if rewritten <> package then
              add `INFO ~file:(dune_file (target_dir tg)) ~target:tg.Target.name
                "package %S is not a dune library name; using %S." package rewritten;
            Some rewritten
        | None ->
            add `INFO ~file:(dune_file (target_dir tg)) ~target:tg.Target.name
              "package %S provides nothing to link; dropped." package;
            None
      end
    in
    let from_libs =
      Utils.split "[ \t\r\n]+" tg.Target.libs
      |> List.filter_map begin fun archive ->
        let base = Filename.basename archive in
        if List.mem base internal_libraries then Some base
        else begin
          match rewrite_library base with
          | Some rewritten ->
              if rewritten <> archive then
                add `INFO ~file:(dune_file (target_dir tg)) ~target:tg.Target.name
                  "required library %S resolved to dune library %S." archive rewritten;
              Some rewritten
          | None -> None
        end
      end
    in
    let from_includes =
      Utils.split "[ \t\r\n]+" tg.Target.includes
      |> List.filter_map begin fun include_dir ->
        if include_dir = "" then None
        else if include_dir.[0] = '+' then
          rewrite_library (String.sub include_dir 1 (String.length include_dir - 1))
        else List.assoc_opt (Rel.from ~dir:"." include_dir) library_of_dir
      end
    in
    let from_dependencies =
      Target.find_target_dependencies targets tg
      |> List.filter_map begin fun dep ->
        if is_library dep then Some (dune_name dep)
        else begin
          add `INFO ~file:(dune_file (target_dir tg)) ~target:tg.Target.name
            "depends on %S, which is not a library; a dune stanza cannot depend \
             on it. Generation rules establish the ordering instead."
            dep.Target.name;
          None
        end
      end
    in
    let unknown =
      tg.Target.dependencies
      |> List.filter (fun id -> not (List.exists (fun t -> t.Target.id = id) targets))
    in
    if unknown <> [] then
      add `WARN ~file:(dune_file (target_dir tg)) ~target:tg.Target.name
        "unknown dependency id%s %s; ignored."
        (if List.length unknown > 1 then "s" else "")
        (String.concat ", " (List.map string_of_int unknown));
    let from_thread = if tg.Target.thread then ["threads.posix"] else [] in
    let all = from_packages @ from_libs @ from_includes @ from_dependencies @ from_thread in
    let all = all |> List.filter (fun lib -> lib <> name) |> Utils.ListExt.remove_dupl in
    let internal, external_ = List.partition (fun lib -> List.mem lib internal_libraries) all in
    List.sort compare internal @ List.sort compare external_
  in

  (* Dune requires every module of a directory to belong to exactly one stanza.
     Rather than asking ocamldep for each target's closure -- which is slow, is
     wrong for modules two targets can reach, and is truncated before the
     generation rules have run -- the library takes everything except the root
     modules of its siblings. *)
  let modules_field dir siblings tg =
    let own = target_files tg |> List.map module_of_path in
    match siblings with
    | [] -> Sexp.field "modules" [Sexp.A ":standard"]
    | _ when is_library tg ->
        let excluded =
          siblings
          |> List.filter (fun other -> not (is_library other))
          |> List.concat_map (fun other -> target_files other |> List.map module_of_path)
        in
        (* A source run as a script by a rule is an input to that rule, not a
           module of the library. It is recognized by appearing among a task's
           arguments: being merely a dependency is not enough, since the sources
           inlined into oebuild_script.ml are ordinary library modules. *)
        let scripts =
          targets
          |> List.concat_map (fun t -> t.Target.external_tasks)
          |> List.concat_map begin fun task ->
            let task_dir = if task.Task.et_dir = "" then "." else task.Task.et_dir in
            Task.enabled task.Task.et_args
            |> List.filter (fun argument -> Filename.check_suffix argument ".ml")
            |> List.map (fun argument -> Rel.from ~dir:"." (task_dir // argument))
          end
          |> List.filter (fun path -> Rel.dirname path = dir)
          |> List.map module_of_path
          |> List.filter begin fun name ->
            not (List.exists
                   (fun t -> List.mem name (target_files t |> List.map module_of_path)) targets)
          end
        in
        let excluded = excluded @ scripts in
        let excluded = Utils.ListExt.remove_dupl excluded |> List.sort compare in
        if excluded = [] then Sexp.field "modules" [Sexp.A ":standard"]
        else
          Sexp.field "modules"
            [Sexp.L (Sexp.A ":standard" :: Sexp.A "\\" :: Sexp.atoms excluded)]
    | _ -> Sexp.field "modules" (Sexp.atoms own)
  in

  (* Not expressible in the model: an .mli with no sibling .ml. Omitting it is a
     hard build failure, so it is read off the filesystem. *)
  let modules_without_implementation dir =
    let path = if dir = "." then src else src // dir in
    match Sys.readdir path with
    | entries ->
        entries
        |> Array.to_list
        |> List.filter (fun name -> Filename.check_suffix name ".mli")
        |> List.filter (fun name -> not (Sys.file_exists (path // (Filename.remove_extension name ^ ".ml"))))
        |> List.map Filename.remove_extension
        |> List.sort compare
    | exception Sys_error _ -> []
  in

  let flags_fields tg =
    let native_cflags, cflags = split_native_flags (Shell.parse_args tg.Target.cflags) in
    let native_cflags =
      match tg.Target.inline with
      | Some n -> native_cflags @ ["-inline"; string_of_int n]
      | None -> native_cflags
    in
    let lflags = Shell.parse_args tg.Target.lflags in
    let standard values = Sexp.L (Sexp.A ":standard" :: Sexp.atoms values) in
    (* [:standard] here means dune's own default flags, not those of an (env ...)
       stanza: env only supplies the flags of a stanza that declares none. Dune's
       defaults mark their warnings fatal (the @ in -w @1..3@5..28...), which
       oebuild never does, so the marks are cancelled to keep the two build
       systems agreeing on what is an error. A -warn-error in the target's own
       flags comes later and still wins. *)
    let cflags = "-warn-error" :: "-A" :: cflags in
    [Sexp.field "flags" [standard cflags]]
    @ (if native_cflags = [] then [] else [Sexp.field "ocamlopt_flags" [standard native_cflags]])
    @ (if lflags = [] then []
       else if is_library tg then [Sexp.field "library_flags" [standard lflags]]
       else [Sexp.field "link_flags" [standard lflags]])
  in

  let has_ppx pkg =
    let cmd = Printf.sprintf "ocamlfind printppx %s 2>/dev/null" (Filename.quote pkg) in
    let ic = Unix.open_process_in cmd in
    let out = try String.trim (input_line ic) with End_of_file -> "" in
    let status = Unix.close_process_in ic in
    status = Unix.WEXITED 0 && out <> ""
  in

  let preprocess_field tg =
    let ppx_pkgs =
      Str.split (Utils.regexp "[ ,]+") tg.Target.package
      |> List.filter has_ppx
      |> Utils.ListExt.remove_dupl
    in
    if String.trim tg.Target.pp = "" then
      match ppx_pkgs with
      | [] -> []
      | pkgs ->
          [Sexp.field "preprocess" [Sexp.L (Sexp.A "pps" :: Sexp.atoms pkgs)]]
    else
      match Shell.parse_args tg.Target.pp with
      | [single] when Filename.check_suffix single ".exe"
                   || String.length single > 3 && String.sub single 0 3 = "ppx" ->
          let all_pps = List.sort_uniq String.compare (single :: ppx_pkgs) in
          [Sexp.field "preprocess" [Sexp.L (Sexp.A "pps" :: Sexp.atoms all_pps)]]
      | tokens ->
          [Sexp.field "preprocess"
             [Sexp.L [Sexp.A "action";
                      Sexp.L (Sexp.A "run" :: Sexp.atoms (tokens @ ["%{input-file}"]))]]]  in

  let enabled_if_field tg =
    let file = dune_file (target_dir tg) in
    let conditions =
      tg.Target.restrictions
      |> List.filter_map begin fun restriction ->
        match Restr.of_string restriction with
        | Some condition -> Some condition
        | None ->
            add `WARN ~file ~target:tg.Target.name
              "unrecognized restriction %S; oebuild treats it as false, so the \
               target is disabled." restriction;
            Some (Sexp.A "false")
      end
    in
    match conditions with
    | [] -> []
    | [single] -> [Sexp.field "enabled_if" [single]]
    | many -> [Sexp.field "enabled_if" [Sexp.L (Sexp.A "and" :: many)]]
  in

  (* Modes are only ever widened. In particular a library never gets (modes ...):
     ocamleditor-lib is native-only in the model, and saying so here would make
     its .cma unavailable and break the bytecode executable. *)
  let modes_field tg =
    if is_library tg then []
    else if emit_bytecode_modes && tg.Target.byt then
      [Sexp.field "modes" [Sexp.A "exe"; Sexp.A "byte_complete"]]
    else []
  in

  let public_name_field tg =
    let file = dune_file (target_dir tg) in
    let name = dune_name tg in
    if is_library tg then begin
      if not tg.Target.is_fl_package then []
      else if List.exists (fun p -> p = name || String.length name > String.length p
                                                && String.sub name 0 (String.length p + 1) = p ^ ".")
          packages
      then [Sexp.field "public_name" [Sexp.A name]]
      else begin
        add `WARN ~file ~target:tg.Target.name
          "marked as a findlib package but there is no dune package named %S, so \
           it cannot be published; (public_name) omitted. The findlib installer \
           generated in tools/ is unaffected." name;
        []
      end
    end
    else if packages = [] then begin
      add `WARN ~file ~target:tg.Target.name
        "the project declares no package (no .opam file), so the executable \
         cannot be installed; (public_name) omitted.";
      []
    end
    else [Sexp.field "public_name" [Sexp.A name]]
  in

  let stanza_of_target dir siblings tg =
    let file = dune_file dir in
    let name = dune_name tg in
    let kind, name_field =
      match tg.Target.target_type with
      | Target.Library -> "library", name
      | Target.Plugin ->
          add `INFO ~file ~target:tg.Target.name
            "a plugin is emitted as a library: dune builds the .cmxs itself.";
          "library", name
      | Target.Pack ->
          add `ERROR ~file ~target:tg.Target.name
            "Pack targets are not expressible: -pack has no dune equivalent. \
             Emitted as a wrapped library, which produces a different artifact.";
          "library", name
      | Target.Executable ->
          (* dune wants the module name; outname becomes the installed name. *)
          "executable", (match target_files tg with
              | first :: _ -> module_of_path first
              | [] -> name)
      | Target.External -> assert false
    in
    let wrapped =
      if kind = "library" then
        [Sexp.field "wrapped" [Sexp.A (if tg.Target.target_type = Target.Pack then "true" else "false")]]
      else []
    in
    let without_implementation =
      if kind = "library" then
        match modules_without_implementation dir with
        | [] -> []
        | names -> [Sexp.field "modules_without_implementation" (Sexp.atoms names)]
      else []
    in
    let libraries =
      match libraries_of tg with
      | [] -> []
      | libraries -> [Sexp.field "libraries" (Sexp.atoms libraries)]
    in
    if List.length (target_files tg |> List.map Rel.dirname |> Utils.ListExt.remove_dupl) > 1 then
      add `ERROR ~file ~target:tg.Target.name
        "its modules live in more than one directory; a dune stanza cannot span \
         directories.";
    if tg.Target.vmthread then
      add `WARN ~file ~target:tg.Target.name "vmthread was removed from OCaml; ignored.";
    if String.trim tg.Target.other_objects <> "" then
      add `WARN ~file ~target:tg.Target.name
        "other required object files (%S) have no dune equivalent; ignored."
        tg.Target.other_objects;
    Sexp.L (Sexp.A kind
            :: Sexp.field "name" [Sexp.A name_field]
            :: public_name_field tg
            @ wrapped
            @ modes_field tg
            @ [modules_field dir siblings tg]
            @ without_implementation
            @ libraries
            @ preprocess_field tg
            @ flags_fields tg
            @ enabled_if_field tg)
  in

  (* Tasks.

     A task that declares outputs becomes a rule, and dune then orders it from
     the dependency graph, which is why the phase mostly stops mattering. One
     without outputs is a command: it becomes an alias, and only runs on
     request. *)
  let alias_of_task tg task =
    sprintf "oe-%s-%s" (sanitize ~sep:'-' tg.Target.name) (sanitize ~sep:'-' task.Task.et_name)
  in
  let action_of_task ~dir tg task =
    let command =
      Sexp.L (Sexp.A "run" :: Sexp.A task.Task.et_cmd
              :: Sexp.atoms (Task.enabled task.Task.et_args))
    in
    let command =
      List.fold_right begin fun variable action ->
        match String.index_opt variable '=' with
        | Some i ->
            Sexp.L [Sexp.A "setenv";
                    Sexp.A (String.sub variable 0 i);
                    Sexp.A (String.sub variable (i + 1) (String.length variable - i - 1));
                    action]
        | None -> action
      end (Task.enabled task.Task.et_env) command
    in
    if task.Task.et_env_replace then
      add `WARN ~file:(dune_file dir) ~target:tg.Target.name ~task:task.Task.et_name
        "replacing the environment instead of extending it is not expressible in \
         dune; the inherited environment is kept.";
    let chdir = Rel.from ~dir (if task.Task.et_dir = "" then "." else task.Task.et_dir) in
    if chdir = "." then command else Sexp.L [Sexp.A "chdir"; Sexp.A chdir; command]
  in
  let deps_of_task ~dir task =
    Task.enabled task.Task.et_deps
    |> List.map begin fun dep ->
      if String.length dep > 0 && dep.[0] = '(' then Sexp.A dep
      else begin
        let absolute = src // dep in
        let rebased = Rel.from ~dir dep in
        if (try Sys.is_directory absolute with Sys_error _ -> false)
        then Sexp.L [Sexp.A "source_tree"; Sexp.A rebased]
        else Sexp.A rebased
      end
    end
  in
  (* Which directory hosts a task's rule: the one holding its outputs, since a
     dune rule may only produce targets in its own directory. *)
  let task_dir tg task =
    match Task.enabled task.Task.et_outputs with
    | [] -> if tg.Target.target_type = Target.External then "." else target_dir tg
    | outputs -> Rel.dirname (List.hd outputs)
  in
  let rule_of_task tg task =
    let dir = task_dir tg task in
    let file = dune_file dir in
    let outputs = Task.enabled task.Task.et_outputs in
    let elsewhere = outputs |> List.filter (fun o -> Rel.dirname o <> dir) in
    if elsewhere <> [] then
      add `ERROR ~file ~target:tg.Target.name ~task:task.Task.et_name
        "declares outputs in more than one directory (%s); a dune rule can only \
         produce targets in its own. Split the task."
        (String.concat ", " elsewhere);
    let action = Sexp.field "action" [action_of_task ~dir tg task] in
    let rule =
      match outputs with
      | [] ->
          let alias = alias_of_task tg task in
          begin
            match task.Task.et_phase with
            | Some phase ->
                add `WARN ~file ~target:tg.Target.name ~task:task.Task.et_name
                  "declares no outputs, so phase %s cannot be represented; \
                   emitted as alias @%s. It runs inside dune's build directory, \
                   so anything it does to the source tree will not behave as it \
                   does under oebuild."
                  (Task.string_of_phase phase) alias
            | None ->
                add `INFO ~file ~target:tg.Target.name ~task:task.Task.et_name
                  "has no phase; reachable only through `dune build @%s'." alias
          end;
          Sexp.L [Sexp.A "rule"; Sexp.field "alias" [Sexp.A alias]; action]
      | outputs ->
          let outputs = outputs |> List.filter (fun o -> Rel.dirname o = dir) in
          let targets = Sexp.field "targets" (Sexp.atoms (List.map Filename.basename outputs)) in
          let deps =
            match deps_of_task ~dir task with
            | [] ->
                add `WARN ~file ~target:tg.Target.name ~task:task.Task.et_name
                  "declares outputs but no dependencies, so dune cannot tell when \
                   to re-run it.";
                []
            | deps -> [Sexp.field "deps" deps]
          in
          Sexp.L (Sexp.A "rule" :: targets :: deps @ [action])
    in
    dir, sprintf "; target %S / task %S\n%s" tg.Target.name task.Task.et_name (Sexp.to_string rule)
  in

  (* A stanza is identified by its kind and its dune name, and two targets can
     land on the same one: in dune the bytecode and native builds of a program are
     modes of a single stanza, not two targets. Emitting both would be rejected,
     so they are merged. *)
  let stanza_key tg =
    (if is_library tg then "library" else "executable"),
    (if is_library tg then dune_name tg
     else match target_files tg with first :: _ -> module_of_path first | [] -> dune_name tg)
  in
  let group_by_stanza here =
    List.fold_left begin fun groups tg ->
      let key = stanza_key tg in
      match List.assoc_opt key groups with
      | Some members -> (key, members @ [tg]) :: List.remove_assoc key groups
      | None -> groups @ [key, [tg]]
    end [] here
  in
  let merge dir = function
    | [single] -> single
    | group ->
        let primary =
          match List.find_opt (fun tg -> tg.Target.default) group with
          | Some tg -> tg
          | None ->
              List.fold_left
                (fun best tg -> if tg.Target.id < best.Target.id then tg else best)
                (List.hd group) group
        in
        let join separator field =
          group
          |> List.map field
          |> List.filter (fun value -> String.trim value <> "")
          |> String.concat separator
        in
        add `INFO ~file:(dune_file dir) ~target:primary.Target.name
          "targets %s map to the same dune stanza and were merged. In dune the \
           byt/opt variants of a program are (modes ...) on one stanza, not two \
           targets."
          (String.concat ", " (List.map (fun tg -> sprintf "%S" tg.Target.name) group));
        { primary with
          Target.byt = List.exists (fun tg -> tg.Target.byt) group;
          opt = List.exists (fun tg -> tg.Target.opt) group;
          thread = List.exists (fun tg -> tg.Target.thread) group;
          libs = join " " (fun tg -> tg.Target.libs);
          package = join "," (fun tg -> tg.Target.package);
          includes = join " " (fun tg -> tg.Target.includes);
          dependencies =
            group |> List.concat_map (fun tg -> tg.Target.dependencies)
            |> Utils.ListExt.remove_dupl }
  in

  (* Group everything by directory. *)
  let buildable = targets |> List.filter (fun tg -> tg.Target.target_type <> Target.External) in
  let dirs_of_targets = buildable |> List.map target_dir |> Utils.ListExt.remove_dupl in
  let rules =
    targets
    |> List.concat_map (fun tg -> tg.Target.external_tasks |> List.map (rule_of_task tg))
  in
  let dirs =
    (dirs_of_targets @ List.map fst rules) |> Utils.ListExt.remove_dupl |> List.sort compare
  in
  let files =
    dirs |> List.map begin fun dir ->
      let file = dune_file dir in
      let here = buildable |> List.filter (fun tg -> target_dir tg = dir) in
      let stanzas =
        group_by_stanza here |> List.map begin fun (_, group) ->
          let tg = merge dir group in
          let siblings = List.filter (fun other -> not (List.memq other group)) here in
          Sexp.to_string (stanza_of_target dir siblings tg)
        end
      in
      let rules = rules |> List.filter (fun (d, _) -> d = dir) |> List.map snd in
      let notes =
        !diagnostics
        |> List.rev
        |> List.filter (fun d -> d.dg_file = file)
        |> List.map begin fun d ->
          sprintf "; %s: %s%s" (string_of_severity d.dg_severity)
            (if d.dg_task <> "" then sprintf "task %S: " d.dg_task
             else if d.dg_target <> "" then sprintf "target %S: " d.dg_target
             else "")
            d.dg_message
        end
      in
      let include_file = if dir = "." then src // "dune.inc" else src // dir // "dune.inc" in
      let user_section =
        if Sys.file_exists include_file
        then ["; --- user section ---\n(include dune.inc)"] else []
      in
      let header = [marker; sprintf "; Source: %s%s" proj.Prj.name Prj.default_extension] in
      let blocks = rules @ stanzas @ user_section in
      file,
      String.concat "\n" (header @ notes) ^ "\n\n" ^ String.concat "\n\n" blocks ^ "\n"
    end
  in
  files, List.rev !diagnostics

(** Writing *)

(* Writes <dir>/dune.generated instead of <dir>/dune and skips the cleanup pass,
   so a generated tree can be compared with a hand-written one. *)
let dry_run = ref (try Sys.getenv "OCAMLEDITOR_DUNE_DRY_RUN" <> "" with Not_found -> false)

let first_line filename =
  let chan = open_in_bin filename in
  let line = try Some (input_line chan) with End_of_file -> None in
  close_in_noerr chan;
  line

let is_generated filename =
  match first_line filename with
  | Some line -> String.trim line = marker
  | None -> false

let read_file filename =
  try Some (Buffer.contents (File_util.read filename)) with Sys_error _ -> None

let write proj =
  let files, diagnostics = render proj in
  let diagnostics = ref (List.rev diagnostics) in
  let add severity ?(file="") fmt =
    ksprintf begin fun message ->
      diagnostics := { dg_severity = severity; dg_file = file; dg_target = "";
                       dg_task = ""; dg_message = message } :: !diagnostics
    end fmt
  in
  let generated = ref [] and changed = ref [] and removed = ref [] in
  files |> List.iter begin fun (relative, content) ->
    let relative = if !dry_run then relative ^ ".generated" else relative in
    let filename = proj.Prj.root // relative in
    generated := filename :: !generated;
    let existing = if Sys.file_exists filename then read_file filename else None in
    match existing with
    | Some previous when previous = content -> ()
    | Some _ when not (is_generated filename) ->
        add `ERROR ~file:relative
          "exists and was not generated by OCamlEditor, so it was left alone. \
           Delete it to hand the directory over to the generator."
    | Some _ when not (File_util.is_writeable filename) ->
        add `ERROR ~file:relative "is not writeable."
    | _ ->
        (* Through a temporary file, so an interrupted write cannot leave a
           truncated dune file behind. *)
        let temporary = sprintf "%s.tmp.%d" filename (Unix.getpid ()) in
        begin
          try
            File_util.write temporary content;
            if Sys.file_exists filename then Sys.remove filename;
            Sys.rename temporary filename;
            changed := relative :: !changed
          with exn ->
            (try Sys.remove temporary with Sys_error _ -> ());
            add `ERROR ~file:relative "cannot be written: %s" (Printexc.to_string exn)
        end
  end;
  (* A target that goes away must take its stanza with it, or the stale file
     breaks the whole build. Only marker-bearing files under the source
     directory are considered, so dune-project and hand-written files are safe. *)
  if not !dry_run then begin
    let src = proj.Prj.root // Prj.default_dir_src in
    File_util.readdirs (Some (fun name -> Filename.basename name = "dune")) src
    |> List.iter begin fun filename ->
      if not (List.mem filename !generated) && is_generated filename then begin
        let relative = Utils.filename_relative proj.Prj.root filename in
        let relative = Option.value relative ~default:filename in
        try
          Sys.remove filename;
          removed := relative :: !removed
        with Sys_error message -> add `WARN ~file:relative "cannot be removed: %s" message
      end
    end
  end;
  { oc_changed = List.rev !changed;
    oc_removed = List.rev !removed;
    oc_diagnostics = List.rev !diagnostics }
